config/routes.rb
Rails.application.routes.draw do
  resources :resumes do
    get 'print_resume', action: 'print'
  end

  resources :experience
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    authenticated :user do
      root 'resumes#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/education.rb
class Education < ApplicationRecord

  belongs_to :resume, optional: true


  validates :degree, presence: true
  validates :institute, presence: true
  validates :major_subjects, presence: true
  validates :sart_date, presence: true
  validates :sart_date,
  :date => { :before => Time.now }
  validates :end_date, presence: true
  validates :end_date,
  :date => { :after => :sart_date, :before => Time.now }
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :resume, optional: true


  validates :title, presence: true
  validates :skills, presence: true
  validates :sart_date, presence: true
  validates :sart_date,
  :date => { :before => Time.now }
  validates :end_date, presence: true
  validates :end_date,
  :date => { :after => :sart_date, :before => Time.now }
end

app/models/language.rb
class Language < ApplicationRecord

  belongs_to :resume, optional: true

  enum level: [:biggner, :intermidiate, :professional, :native]
  validates :language, presence: true
  validates :level, presence: true
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user

  has_many :experiences, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_many :languages, dependent: :destroy

  has_one_attached :picture, dependent: :purge_later

  after_create_commit :add_serial_number_to_resume
  accepts_nested_attributes_for :experiences, allow_destroy: true, :reject_if => :all_blank
  accepts_nested_attributes_for :educations, allow_destroy: true, :reject_if => :all_blank
  accepts_nested_attributes_for :languages, allow_destroy: true, :reject_if => :all_blank

  validates :first_name, presence: true, length: {minimum: 3, maximum: 20}
  validates :picture, presence: true
  validates :last_name, presence: true, length: {minimum: 3, maximum: 20}
  validates :discription, presence: true, length: {minimum: 20, maximum: 500}
  validates :phone, presence: true, length: {minimum: 9, maximum: 15}
  validates :adress, presence: true
  validates :designation, presence: true
  validates :skills, presence: true
  validates :email,presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def add_serial_number_to_resume
    self.serial_number = "PM-#{user_id}-#{id}"
    self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :resumes
  has_one_attached :avatar, dependent: :purge_later

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: %i[avatar])
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:error] = "You are not authorized to perform this action...!"
    redirect_back(fallback_location: unauthenticated_root_path)
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: %i[ show edit update destroy ]


  def index
    @resumes = current_user.resumes
    authorize @resumes
  end

  def print
    @resume = Resume.find(params[:resume_id])

    respond_to do |format|
        format.html
        format.pdf do
            render pdf: "Resume No. #{@resume.id}",
            page_size: 'A4',
            template: "resumes/print.html.erb",
            layout: "pdf.html",
            orientation: "Landscape",
            lowquality: true,
            zoom: 1,
            dpi: 75
        end
    end
  end

  def show
    authorize @resume
  end

  def new
    @resume = Resume.new
    authorize @resume
  end

  def edit
    authorize @resume
  end

  def create
    @resume = Resume.new(resume_params)
    authorize @resume
    @resume.user_id = current_user.id

    respond_to do |format|
      if @resume.save
        format.html { redirect_to resume_path(@resume), notice: "Resume was successfully created." }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @resume
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to resume_url(@resume), notice: "Resume was successfully updated." }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @resume
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: "Resume was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_resume
      @resume = Resume.find(params[:id])
    end

    def resume_params
      params.require(:resume).permit(:first_name, :picture, :last_name, :discription, :serial_number, :phone, :adress, :email, :designation, :skills, experiences_attributes: [:id, :title, :skills, :sart_date, :end_date, :_destroy],  educations_attributes: [:id, :degree, :institute, :major_subjects, :sart_date, :end_date, :_destroy], languages_attributes: [:id, :language, :level, :_destroy] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experience_helper.rb
module ExperienceHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ResumeBuilder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <nav class='navbar navbar-expand-lg navbar-light bg-light'>
      <ul class='navbar-nav'>
        <li class='nav-item'>
        <a class='nav-link' id='navbarDropdownMenuLink' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
        <% if user_signed_in? %>
          <% if current_user.avatar.attached? %>
            <%= image_tag current_user.avatar, class: 'rounded-circle User-image'%>
          <% else %>
            <%= image_tag 'download.png', class: 'rounded-circle User-image' %>
          <% end %>
        <% else %>
          <%= image_tag 'fox.jpg', class: 'rounded-circle User-image' %>
        <% end %>
        </a>
        <% if user_signed_in? %>
          <div class='dropdown-menu' aria-labelledby='navbarDropdownMenuLink'>
            <%= link_to 'Edit Profile', edit_user_registration_url, class: 'dropdown-item' %>
            <%= link_to 'Log out', destroy_user_session_path, class: 'dropdown-item' %>
          </div>
        <%else %>
          <div class='dropdown-menu' aria-labelledby='navbarDropdownMenuLink'>
            <%= link_to 'Log In', new_user_session_path , class: 'dropdown-item' %>
            <%= link_to 'Sign Up ', new_user_registration_path , class: 'dropdown-item' %>
          </div>
        <% end %>
        </li>
      </ul>
      <ul class='navbar-nav ml-auto'>
        <li class='nav-item'>
          <%= link_to 'Home', authenticated_root_path, class: 'nav-link' %>
        </li>


          <% if user_signed_in? %>
          <li class='nav-item'>
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %>
          </li>
          <li class='nav-item'>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
          </li>
        <% else %>
        <li class='nav-item'>
        <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %>
        </li>
        <li class='nav-item'>
        <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
        </li>
        <% end %>
      </ul>

    </nav>

      <% flash.each do |type, msg| %>
        <% if type == 'alert' %>
          <div class="alert alert-danger">
            <%= msg %>
          </div>
        <% else %>
        <div class="alert alert-info">
            <%= msg %>
          </div>
        <% end %>
      <% end %>


    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PDFs - Ruby on Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= wicked_pdf_stylesheet_link_tag "application" %>
</head>
<body>
    <%= yield %>
</body>
</html>

app/views/resumes/_education.html.erb
<p> <strong>Degree</strong> : <%= education.degree %></p>
<ul>
<li class="m-0">Institute : <%= education.institute %></li>
<li class="m-0">Major subjects : <%= education.major_subjects %></li>
<li class="m-0">Started on : <%= education.sart_date %></li>
<li class="m-0">Ended on : <%= education.end_date %></li>
<li class="m-0 mb-3">Total Duration : <%= distance_of_time_in_words(education.end_date , education.sart_date) %></li>
</ul>

app/views/resumes/_education_fields.html.erb
<div class='nested-fields'>
  <%= f.input :degree,required: false %>
  <%= f.input :institute, required: false %>
  <%= f.input :major_subjects, required: false %>
  <%= f.input :sart_date , required: false, :input_html => { :class => 'date' }  %>
  <%= f.input :end_date , required: false, :input_html => { :class => 'date' }  %>
  <%= link_to_remove_association 'Remove Education', f %>
</div>

app/views/resumes/_experience.html.erb
<p> <strong>Title</strong> : <%= experience.title %></p>
<ul>
<li class="m-0">Skills : <%= experience.skills %></li>
<li class="m-0">Started on : <%= experience.sart_date %></li>
<li class="m-0">Ended on : <%= experience.end_date %></li>
<li class="m-0 mb-3">Experience Time : <%= distance_of_time_in_words(experience.end_date , experience.sart_date) %></li>
</ul>

app/views/resumes/_experience_fields.html.erb
<div class='nested-fields'>
  <%= f.input :title,required: false %>
  <%= f.input :skills, required: false %>
  <%= f.input :sart_date , required: false, :input_html => { :class => 'date' }  %>
  <%= f.input :end_date , required: false, :input_html => { :class => 'date' }  %>
  <%= link_to_remove_association 'Remove experience', f %>
</div>

app/views/resumes/_form.html.erb
<%= simple_form_for(@resume) do |form| %>
  <% if @resume.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
          <% @resume.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div>
    <%= form.input :picture, as: :file %>
    <%= form.input :first_name , :input_html => {maxlength: 20, minlength: 3} %>
    <%= form.input :last_name , required: true, :input_html => {maxlength: 20, minlength: 3} %>
    <%= form.input :discription,required: true,  :input_html => {maxlength: 500, minlength: 3} %>
    <%= form.input :phone, required: true, input_html: { type: 'number', maxlength: 15, minlength: 9} %>
    <%= form.input :adress, required: true, :input_html => {maxlength: 50, minlength: 10} %>
    <%= form.input :email , required: true, :input_html => {maxlength: 50, minlength: 7} %>
    <%= form.input :designation, required: true, :input_html => {maxlength: 50, minlength: 2} %>
    <%= form.input :skills, required: true, :input_html => {maxlength: 50, minlength: 3} %>
  </div>

  <div class='education'>
    <h4>Education</h4>
    <%= form.simple_fields_for :educations do |education| %>
      <%= render "education_fields", f: education %>
    <% end %>
  </div>
  <%= link_to_add_association 'Add education', form , :educations,class: 'btn', data: {  association_insertion_node: 'div.education' , association_insertion_method: :append } %>

  <div class='experience'>
    <h4>Experience</h4>
    <%= form.simple_fields_for :experiences do |experience| %>
      <%= render "experience_fields", f: experience %>
    <% end %>
  </div>
    <%= link_to_add_association 'Add experience', form , :experiences,class: 'btn', data: {  association_insertion_node: 'div.experience' , association_insertion_method: :append } %>

  <div class='language'>
    <h4>Language</h4>
    <%= form.simple_fields_for :languages do |language| %>
      <%= render "language_fields", f: language %>
    <% end %>
  </div>
  <%= link_to_add_association 'Add Language', form , :languages,class: 'btn', data: {  association_insertion_node: 'div.language' , association_insertion_method: :append } %>

  <div>
    <%= form.button :submit%>
  </div>
<% end %>

app/views/resumes/_language.html.erb
<p> <strong><%= language.language.upcase %> </strong></p>
<ul>
<li class="m-0">Level : <%= language.level %></li>
</ul>

app/views/resumes/_language_fields.html.erb
<div class='nested-fields'>
  <%= f.input :language,required: false %>
  <%= f.input :level, :collection => %w[biggner intermidiate professional native] %>
  <%= link_to_remove_association 'Remove Language', f %>
</div>

app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resumes</h1>
<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Discription</th>
      <th>Serial number</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.first_name %></td>
        <td><%= resume.last_name %></td>
        <td><%= resume.discription %></td>
        <td><%= resume.serial_number %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Resume', new_resume_path %>

app/views/resumes/new.html.erb
<h1>New Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Back', resumes_path %>

app/views/resumes/print.html.erb
<div class="header  bg-primary text-white row">
    <div class="col-md-1 col-lg-1"></div>
    <div class="name col-md-5 col-lg-4 p-5">
      <h1> <%= @resume.first_name %></h1>
      <h1> <%= @resume.last_name %>  </h1>
    </div>
    <div class="contact col-md-2 col-lg-2 p-4">
      <% if(@resume.picture.attached?) %>
        <%=  image_tag @resume.picture , class: 'User-image-cv rounded-circle' %>
      <% end %>
    </div>
    <div class="contact text-end col-md-4 col-lg-4 p-4">
      <div class="Adress"> <p class="fw-bold m-0"> Adress</p> <p class="fw-lighter"><%= @resume.adress %> </p> </div>
      <div class="phone"> <p class="fw-bold m-0">Phone</p> <p class="fw-lighter"> <%= @resume.phone %> </p></div>
      <div class="email"> <p class="fw-bold m-0">Email</p> <p class="fw-lighter"><%= @resume.email %></p></div>
    </div>
  </div>
  <div class="body m-5">
    <div class="summery">
      <h4 class="fw-bold m-0 mt-2">Summery</h4>
      <hr class="bg-dark border-2 border-top border-dark m-0 mb-2">
      <div class="col-md-10 col-lg-10 text-wrap text-break"><%= @resume.discription %></div>
    </div>
    <div class="Education">
      <h4 class="fw-bold m-0 mt-2">Education</h4>
      <hr class="bg-dark border-2 border-top border-dark m-0 mb-2">
      <p>
        <%= render partial: "education", collection: @resume.educations %>
      </p>
    </div>
    <div class="Experience">
      <h4 class="fw-bold m-0 mt-2">Experiences</h4>
      <hr class="bg-dark border-2 border-top border-dark m-0 mb-2">
      <p>
      <%= render partial: "experience", collection: @resume.experiences %>
      </p>
    </div>
    <%# <div class="certificate">
      <h4 class="fw-bold m-0 mt-2"> Certificates </h4>
      <hr class="bg-dark border-2 border-top border-dark m-0 mb-2">
      <p>
      </p>
    </div> %>
    <div class="skills">
    <h4 class="fw-bold m-0 mt-2"> Skills </h4>
      <hr class="bg-dark border-2 border-top border-dark m-0 mb-2">
      <% skills = @resume.skills.split(',') %>
      <ul class="row">
       <% skills.each do |skill|  %>
        <li class="col-md-5 col-lg-5"><%= skill.upcase %></li>
        <% end %>
      </ul>
    </div>
    <div class="language">
      <h4 class="fw-bold m-0 mt-2">Languages</h4>
      <hr class="bg-dark border-2 border-top border-dark m-0 mb-2">
      <p>
      <%= render partial: "language", collection: @resume.languages %>
      </p>
    </div>
  </div>
  <div class="header  bg-primary text-white row">
    <br><br>
  </div>

app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container ">
  <div class="header  bg-primary text-white row">
    <div class="col-md-1 col-lg-1"></div>
    <div class="name col-md-5 col-lg-4 p-5">
      <h1> <%= @resume.first_name %></h1>
      <h1> <%= @resume.last_name %>  </h1>
    </div>
    <div class="contact col-md-2 col-lg-2 p-4">
      <% if(@resume.picture.attached?) %>
        <%=  image_tag @resume.picture , class: 'User-image-cv rounded-circle' %>
      <% end %>
    </div>
    <div class="contact text-end col-md-4 col-lg-4 p-4">
      <div class="Adress"> <p class="fw-bold m-0"> Adress</p> <p class="fw-lighter"><%= @resume.adress %> </p> </div>
      <div class="phone"> <p class="fw-bold m-0">Phone</p> <p class="fw-lighter"> <%= @resume.phone %> </p></div>
      <div class="email"> <p class="fw-bold m-0">Email</p> <p class="fw-lighter"><%= @resume.email %></p></div>
    </div>
  </div>
  <div class="body m-5">
    <div class="summery">
      <h4 class="fw-bold m-0 mt-2">Summery</h4>
      <hr class="bg-dark border-2 border-top border-dark m-0 mb-2">
      <div class="col-md-10 col-lg-10 text-wrap text-break"><%= @resume.discription %></div>
    </div>
    <div class="Education">
      <h4 class="fw-bold m-0 mt-2">Education</h4>
      <hr class="bg-dark border-2 border-top border-dark m-0 mb-2">
      <p>
        <%= render partial: "education", collection: @resume.educations %>
      </p>
    </div>
    <div class="Experience">
      <h4 class="fw-bold m-0 mt-2">Experiences</h4>
      <hr class="bg-dark border-2 border-top border-dark m-0 mb-2">
      <p>
      <%= render partial: "experience", collection: @resume.experiences %>
      </p>
    </div>
    <%# <div class="certificate">
      <h4 class="fw-bold m-0 mt-2"> Certificates </h4>
      <hr class="bg-dark border-2 border-top border-dark m-0 mb-2">
      <p>
      </p>
    </div> %>
    <div class="skills">
    <h4 class="fw-bold m-0 mt-2"> Skills </h4>
      <hr class="bg-dark border-2 border-top border-dark m-0 mb-2">
      <% skills = @resume.skills.split(',') %>
      <ul class="row">
       <% skills.each do |skill|  %>
        <li class="col-md-5 col-lg-5"><%= skill.upcase %></li>
        <% end %>
      </ul>
    </div>
    <div class="language">
      <h4 class="fw-bold m-0 mt-2">Languages</h4>
      <hr class="bg-dark border-2 border-top border-dark m-0 mb-2">
      <p>
      <%= render partial: "language", collection: @resume.languages %>
      </p>
    </div>
  </div>
  <div class="header  bg-primary text-white row">
    <br><br>
  </div>
</div>

<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>
<%= link_to 'Destroy', @resume, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'DOWNLOAD PDF',  resume_print_resume_path(@resume, format: :pdf) %>